### ISSUE TITLE
Xbox support?

### ISSUE THREAD

**Issue by not-relevant92** [ohhsodead/arisen-gsc-injector#1]
Will you be adding Xbox support in the future at anytime?

**Comment by ohhsodead** [comment]
@not-relevant92 What are the connection methods for xbox? I can have a look into implementing this. But I see xbox gsc tools are a little scarce, especially open source ones.

**Comment by ohhsodead** [comment]
@not-relevant92 I've added support for xbox now (I think), just I need someone to test this out for me.

**Comment by not-relevant92** [comment]
@ohhsodead Not relevant to the xbox part of thing, however DarkDataGridView in your source code does not work, please update!

**Comment by ohhsodead** [comment]
@not-relevant92 I haven't changed any code from the original source since I found that fork.
