### ISSUE TITLE
Impossible to load CCAPI 2.60

### ISSUE THREAD

**Issue by thevalo** [ohhsodead/arisen-gsc-injector#15]
Hi, I'm trying to connect via Connect > PS3 > Connect using Control Console but it doesn't work. There are displayed two error dialog boxes with message "impossible to load CCAPI 2.60"

I have installed CCAPI on default directory, AppData/Roaming... and I tried to run it via administrator privilege, but to no avail.

See the attached screenshot:
![image](https://user-images.githubusercontent.com/28608203/233842761-645b0c6e-c991-4690-b8a9-1a925609db34.png)

**Comment by ohhsodead** [comment]
@thevalo are you using the latest version? Alternatively, if you have webman installed you can use the PS3MAPI option to connect

**Comment by thevalo** [comment]
I am using the latest version, I've checked even with the "Check Updates" function.

I have webMan and I'll try tonight hopefully and let you know.

By the way, I have CCAPI 2.80 on the PS3, and I had to downgrade CCAPI from 2.80 to 2.60 in PC, seems like it's a requirement for the injector to work. I don't think this would interfere anyhow? I have used successfully another injector (project iconic) in the same way (2.60 on PC and 2.80 on PS3) and it worked great. 

I have no antivirus active in the system either. 

Seems like it's CCAPI lib used in the injector itself? [Please see this](https://github.com/FrenchModdingTeam/PS3Lib/blob/c2110c3871c55a1e5de5d28d66ae7622f7790d5b/demo/CCAPI-Demo/CCAPI-Demo/PS3Lib/API/CCAPI.cs#L153).

OS: Win10 x64

**Comment by thevalo** [comment]
@ohhsodead for the webMAN, which one should I choose? Target Manager, or PS3 Manager? Although none of them work either.

**Comment by ohhsodead** [comment]
Hi @thevalo sorry for the late reply, PS3 Manager option would be the one to use for connecting with webMAN

**Comment by ohhsodead** [comment]
do you have discord? maybe we can follow up there

**Comment by thevalo** [comment]
> do you have discord? maybe we can follow up there

Yes, please send me your discord username and I'll message you. Thanks!

**Comment by ohhsodead** [comment]
> > do you have discord? maybe we can follow up there
> 
> Yes, please send me your discord username and I'll message you. Thanks!

It's the same as my GitHub username :)
