### ISSUE TITLE
Solution doesn't build without modified DarkUI control?

### ISSUE THREAD

**Issue by danielj23** [ohhsodead/arisen-gsc-injector#3]
I went to download the solution and added the DarkUI project, but it seems there is a modification that isn't available with the DataGridview. 

 I really just got here because you seemed to get [an answer to your question](https://github.com/RobinPerris/DarkUI/issues/11) about the DarkScrollbar that i was hoping to look at how you accomplished it.

Can you post the modified source to DarkUI so I can load your solution?

**Comment by ohhsodead** [comment]
@danielj23 take a look at my other repo's, I have posted the modified version of DarkUI repo here on my profile. Maybe this will help?

**Comment by danielj23** [comment]
See that now.  Thanks.

**Comment by danielj23** [comment]
@ohhsodead Feel free to ignore but I emailed you on the 14th to see if you were interested in something.  Not trying to bother you, just not sure if you check that email listed on your profile.
