### ISSUE TITLE
[Request] Serenity v4

### ISSUE THREAD

**Issue by ItsPKO** [ohhsodead/arisen-gsc-injector#4]
Enter some information about the mods here, add any links you can find that showcase the mods too.
Game Type: Multiplayer / Zombies
Mod Type: Mod Menu / Game Mode
Author: Creator / Developer
Version: Version
Files: Download Link
----------------------- 
*Please include any other additional information you can find for the mods.

**Comment by ohhsodead** [comment]
@ItsPKO thanks for the request! Please could you provide some links that releases this mod, such as a youtube video or a post on some forum. So that I know what I'm adding to the database.

**Comment by ohhsodead** [comment]
@ItsPKO I can't find this menu anywhere on Google. Could you please provide some links where I can download the menu? Thanks.

**Comment by ohhsodead** [comment]
@ItsPKO Added to database as of 03/11/2020
