### ISSUE TITLE
call of durty ghost mods

### ISSUE THREAD

**Issue by mikeybee23** [ohhsodead/arisen-gsc-injector#5]
Enter some information about the mods here, add any links you can find that showcase the mods too.
Game Type: Multiplayer / Zombies
Mod Type: Mod  / Game Mode
: Creator / Developer
Version: Version
Files: Download Link
----------------------- 
*Please include any other additional information you can find for the mods.

**Comment by ohhsodead** [comment]
@mikeybee23 any mods you can actually suggest? I'll look around but it would be nice if you could provide some links or names for some mods too.

**Comment by ohhsodead** [comment]
Closed as this is a BO2 tool, not for Ghosts.
