### ISSUE TITLE
"unable to inject gsc files. Message:The remote server returned an error: (400) Bad Request."

### ISSUE THREAD

**Issue by natanielczolgowski** [ohhsodead/arisen-gsc-injector#7]
After I connect ccapi and and the injector to my PS3, I try to inject a mod menu and I get "all gsc files have been restored" and then "unable to inject gsc files. Message:The remote server returned an error: (400) Bad Request."

I asked for help in the discord server but nobody responded. Could use a hand if you're available. Thanks!

-----------------------
* Mod Name: All the mods in included
* Game Type: Multiplayer/Zombies
* Mod Type: Mod Menu
* Author:
* Version:
* Download Link:

**Comment by ohhsodead** [comment]
@natanielczolgowski

Hi, thanks for giving feedback. Could you please provide the _log.txt_ file located in the app install path, so I look into this further. Thanks.

**Comment by ohhsodead** [comment]
Also, do u have discord? I have an unreleased version for this app and it may fix this issue. If you're willing to test for me, add my user: ohhsodead#2519 and we can talk there.

**Comment by natanielczolgowski** [comment]
Sure thing, just sent it over via discord.

**Comment by mitchymodz** [comment]
hi all, 

i have just downloaded this program and i am getting the same issue 

could you please help me out
![Atomic X](https://user-images.githubusercontent.com/77569946/104837499-d5d41f80-58ac-11eb-9e09-799ec97b0861.PNG)

**Comment by ohhsodead** [comment]
All has been fixed now.
