### ISSUE TITLE
[Request] Official Mod Name

### ISSUE THREAD

**Issue by MrMcyeet** [ohhsodead/arisen-gsc-injector#9]
Enter some information about the mods here, add any links you can find that showcase the mods too.
Game Type: Multiplayer
Mod Type: Game Mode
Author: Matrix
Version: unknown
Files: https://www.mediafire.com/file/xkku5itga2wsjry/Game_-_Dodgeball.rar/file
----------------------- 
*Please include any other additional information you can find for the mods.
Its a fun mode made by matrix.
i remember playing it back in the day.

**Comment by ohhsodead** [comment]
@MrMcyeet Thanks for the request! I'll get this added soon as I can (:

**Comment by ohhsodead** [comment]
Added to database.
